from django.urls import path, include
from . import views

urlpatterns = [
    path('users/', include('users.urls')),
    path('', views.home, name='home'),  # Home
    path('lista-prendas/', views.lista_prendas, name='lista_prendas'),
    path('editar-prenda/<int:prenda_id>/', views.editar_prenda, name='editar_prenda'),
    path('marcar-vendida/<int:prenda_id>/', views.marcar_como_vendida, name='marcar_como_vendida'),
    path('ventas/', views.ver_ventas, name='ver_ventas'),
    path('marcar-disponible/<int:prenda_id>/', views.marcar_como_disponible, name='marcar_como_disponible'),
    path('ventas/exportar/', views.exportar_ventas_excel, name='exportar_ventas_excel'),
    path('estadisticas/', views.ver_estadisticas, name='estadisticas'),
    path('users/', include('users.urls')),
    path('catalogo/recientes/', views.catalogo_recientes, name='catalogo_recientes'),

    path('contacto/', views.contacto, name='contacto'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('agregar-prenda/', views.agregar_prenda, name='agregar_prenda'),
    path('inventario/', views.ver_inventario, name='ver_inventario'),
    path('eliminar/<int:prenda_id>/', views.eliminar_prenda, name='eliminar_prenda'), #Eliminar prenda

    #catalogooo
    path('catalogo/bebe/bodies', views.catalogo_bebebodies, name='catalogo_bebebodies'),
    path('catalogo/bebe/conjuntos', views.catalogo_bebeconjuntos, name='catalogo_bebeconjuntos'),
    path('catalogo/bebe/pijamas', views.catalogo_bebepijamas, name='catalogo_bebepijamas'),
    path('catalogo/nino/camisas', views.catalogo_niñocamisas, name='catalogo_niñocamisas'),
    path('catalogo/nino/chaquetas', views.catalogo_niñochaquetas, name='catalogo_niñochaquetas'),
    path('catalogo/nino/pantalones', views.catalogo_niñopantalones, name='catalogo_niñopantalones'),
    path('catalogo/nino/zapatos', views.catalogo_niñozapatos, name='catalogo_niñozapatos'),
    path('catalogo/hombre/camisas', views.catalogo_hombrecamisas, name='catalogo_hombrecamisas'),
    path('catalogo/hombre/chaquetas', views.catalogo_hombrechaquetas, name='catalogo_hombrechaquetas'),
    path('catalogo/hombre/pantalones', views.catalogo_hombrepantalones, name='catalogo_hombrepantalones'),
    path('catalogo/hombre/zapatos', views.catalogo_hombrezapatos, name='catalogo_hombrezapatos'),
    path('catalogo/hombre/deportivos', views.catalogo_hombredeportivos, name='catalogo_hombredeportivos'),
    path('catalogo/hombre/blazers', views.catalogo_hombreblazers, name='catalogo_hombreblazers'),
    path('catalogo/mujer/bolsos', views.catalogo_mujerbolsos, name='catalogo_mujerbolsos'),
    path('catalogo/mujer/zapatos', views.catalogo_mujerzapatos, name='catalogo_mujerzapatos'),
    path('catalogo/mujer/sandalias', views.catalogo_mujersandalias, name='catalogo_mujersandalias'),
    path('catalogo/mujer/accesorios', views.catalogo_mujeraccesorios, name='catalogo_mujeraccesorios'),
    path('catalogo/mujer/ropainterior', views.catalogo_mujerropainterior, name='catalogo_mujerropainterior'),
    path('catalogo/mujer/pijamas', views.catalogo_mujerpijamas, name='catalogo_mujerpijamas'),
    path('catalogo/mujer/deportivos', views.catalogo_mujerdeportivos, name='catalogo_mujerdeportivos'),
    path('catalogo/mujer/conjuntos', views.catalogo_mujerconjuntos, name='catalogo_mujerconjuntos'),
    path('catalogo/mujer/trajesdebaño', views.catalogo_mujertrajesdebaño, name='catalogo_mujertrajesdebaño'),
    path('catalogo/mujer/bodies', views.catalogo_mujerbodies, name='catalogo_mujerbodies'),
    path('catalogo/mujer/shorts', views.catalogo_mujershorts, name='catalogo_mujershorts'),
    path('catalogo/mujer/faldas', views.catalogo_mujerfaldas, name='catalogo_mujerfaldas'),
    path('catalogo/mujer/jeans', views.catalogo_mujerjeans, name='catalogo_mujerjeans'),
    path('catalogo/mujer/pantalones', views.catalogo_mujerpantalones, name='catalogo_mujerpantalones'),
    path('catalogo/mujer/vestidos', views.catalogo_mujervestidos, name='catalogo_mujervestidos'),
    path('catalogo/mujer/tops', views.catalogo_mujertops, name='catalogo_mujertops'),
    path('catalogo/mujer/enterizos', views.catalogo_mujerenterizos, name='catalogo_mujerenterizos'),
    path('catalogo/mujer/camisetas', views.catalogo_mujercamisetas, name='catalogo_mujercamisetas'),
    path('catalogo/mujer/camisas', views.catalogo_mujercamisas, name='catalogo_mujercamisas'),
    path('catalogo/mujer/chaquetas', views.catalogo_mujerchaquetas, name='catalogo_mujerchaquetas'),
    path('catalogo/mujer/blusas', views.catalogo_mujerblusas, name='catalogo_mujerblusas'),
]