from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),  # Home
    path('lista-prendas/', views.lista_prendas, name='lista_prendas'), 
    path('contacto/', views.contacto, name='contacto'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('agregar-prenda/', views.agregar_prenda, name='agregar_prenda'),
    path('inventario/', views.ver_inventario, name='ver_inventario'),

    #catalogooo
    path('catalogo/bodies', views.catalogo_bebebodies, name='catalogo_bebebodies'),
    path('catalogo/conjuntos', views.catalogo_bebeconjuntos, name='catalogo_bebeconjuntos'),
    path('catalogo/pijamas', views.catalogo_bebepijamas, name='catalogo_bebepijamas'),
    path('catalogo/camisas', views.catalogo_niñocamisas, name='catalogo_niñocamisas'),
    path('catalogo/chaquetas', views.catalogo_niñochaquetas, name='catalogo_niñochaquetas'),
    path('catalogo/pantalones', views.catalogo_niñopantalones, name='catalogo_niñopantalones'),
    path('catalogo/zapatos', views.catalogo_niñozapatos, name='catalogo_niñozapatos'),
    path('catalogo/camisas', views.catalogo_hombrecamisas, name='catalogo_hombrecamisas'),
    path('catalogo/chaquetas', views.catalogo_hombrechaquetas, name='catalogo_hombrechaquetas'),
    path('catalogo/pantalones', views.catalogo_hombrepantalones, name='catalogo_hombrepantalones'),
    path('catalogo/zapatos', views.catalogo_hombrezapatos, name='catalogo_hombrezapatos'),
    path('catalogo/deportivos', views.catalogo_hombredeportivos, name='catalogo_hombredeportivos'),
    path('catalogo/blazers', views.catalogo_hombreblazers, name='catalogo_hombreblazers'),
path('catalogo/bolsos', views.catalogo_mujerbolsos, name='catalogo_mujerbolsos'),
path('catalogo/zapatos', views.catalogo_mujerzapatos, name='catalogo_mujerzapatos'),
path('catalogo/sandalias', views.catalogo_mujersandalias, name='catalogo_mujersandalias'),
path('catalogo/accesorios', views.catalogo_mujeraccesorios, name='catalogo_mujeraccesorios'),
path('catalogo/ropainterior', views.catalogo_mujerropainterior, name='catalogo_mujerropainterior'),
path('catalogo/pijamas', views.catalogo_mujerpijamas, name='catalogo_mujerpijamas'),
path('catalogo/deportivos', views.catalogo_mujerdeportivos, name='catalogo_mujerdeportivos'),
path('catalogo/conjuntos', views.catalogo_mujerconjuntos, name='catalogo_mujerconjuntos'),
path('catalogo/trajesdebaño', views.catalogo_mujertrajesdebaño, name='catalogo_mujertrajesdebaño'),
path('catalogo/bodies', views.catalogo_mujerbodies, name='catalogo_mujerbodies'),
path('catalogo/shorts', views.catalogo_mujershorts, name='catalogo_mujershorts'),
path('catalogo/faldas', views.catalogo_mujerfaldas, name='catalogo_mujerfaldas'),
path('catalogo/jeans', views.catalogo_mujerjeans, name='catalogo_mujerjeans'),
path('catalogo/pantalones', views.catalogo_mujerpantalones, name='catalogo_mujerpantalones'),
path('catalogo/vestidos', views.catalogo_mujervestidos, name='catalogo_mujervestidos'),
path('catalogo/tops', views.catalogo_mujertops, name='catalogo_mujertops'),
path('catalogo/enterizos', views.catalogo_mujerenterizos, name='catalogo_mujerenterizos'),
path('catalogo/camisetas', views.catalogo_mujercamisetas, name='catalogo_mujercamisetas'),
path('catalogo/camisas', views.catalogo_mujercamisas, name='catalogo_mujercamisas'),
path('catalogo/chaquetas', views.catalogo_mujerchaquetas, name='catalogo_mujerchaquetas'),
path('catalogo/blusas', views.catalogo_mujerblusas, name='catalogo_mujerblusas'),
]