# Generated by Django 5.2 on 2025-05-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
