# Generated by Django 5.2 on 2025-05-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='categoria',
            field=models.CharField(choices=[('Blusas', 'Blusas'), ('Chaquetas', 'Chaquetas'), ('Camisas', 'Camisas'), ('Camisetas', 'Camisetas'), ('Enterizos', 'Enterizos'), ('Tops', 'Tops'), ('Vestidos', 'Vestidos'), ('Pantalones', 'Pantalones'), ('Jeans', 'Jeans'), ('Faldas', 'Faldas'), ('Shorts', 'Shorts'), ('Bodies', 'Bodies'), ('Trajes de baño', 'Trajes de baño'), ('Conjuntos', 'Conjuntos'), ('Deportivos', 'Deportivos'), ('Pijamas', 'Pijamas'), ('Ropa interior', 'Ropa interior'), ('Bolsos y carteras', 'Bolsos y carteras'), ('Zapatos', 'Zapatos'), ('Sandalias', 'Sandalias'), ('Accesorios', 'Accesorios'), ('Camisas hombre', 'Camisas hombre'), ('Chaquetas hombre', 'Chaquetas hombre'), ('Pantalones hombre', 'Pantalones hombre'), ('Zapatos hombre', 'Zapatos hombre'), ('Deportivos hombre', 'Deportivos hombre'), ('Blazers', 'Blazers'), ('Sandalias hombre', 'Sandalias hombre'), ('Accesorios hombre', 'Accesorios hombre'), ('Artículos hogar', 'Artículos hogar'), ('Camisas niño', 'Camisas niño'), ('Pantalones niño', 'Pantalones niño'), ('Chaquetas niño', 'Chaquetas niño'), ('Zapatos niño', 'Zapatos niño'), ('Bodies bebé', 'Bodies bebé'), ('Conjuntos bebé', 'Conjuntos bebé'), ('Pijamas bebé', 'Pijamas bebé')], default='Camisetas', max_length=50),
        ),
    ]
