# Generated by Django 5.1.6 on 2025-05-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='fecha_venta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
