# Generated by Django 5.2.1 on 2025-05-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_prenda_fecha_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
