# Generated by Django 5.2.1 on 2025-05-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_prenda_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
