# Generated by Django 5.1.6 on 2025-05-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_prenda_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='nombre_proveedor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prenda',
            name='precio_proveedor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
